### ISSUE TITLE
[Yes! it is] Is this project being maintained?

### ISSUE THREAD

**Issue by HannanAkbar** [luckyshot/twentyfive#12]
I was wondering whether this project is being maintained or not. Are you accepting pull requests?

**Comment by luckyshot** [comment]
Hi @HannanAkbar ,

Sure! I'm working on other things right now although I'll gladly accept any progress on the project. Feel free to submit your PR :)

**Comment by HannanAkbar** [comment]
That's great! 👍 @luckyshot 
Thanks.
